# Generated by Django 3.2.4 on 2021-06-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0002_alter_emailfiles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailfiles',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
